<div class="modal fade" id="previewModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Предварительный просмотр</h4>
            </div>
            <div class="modal-body">

                <div class="form-group">
                    <label>Имя</label>
                    <input disabled="disabled" type="text" class="form-control" name="name" id="namePreview" placeholder="Имя" />
                </div>
                <div class="form-group">
                    <label>E-mail</label>
                    <input disabled="disabled" type="email" class="form-control" name="email" id="emailPreview" placeholder="E-mail" />
                </div>
                <div class="form-group">
                    <label>Текст сообщения</label>
                    <textarea disabled="disabled" id="textPreview" class="form-control" name="textPreview" rows="3"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" id="sendOk">Отправить</button>
            </div>
        </div>
    </div>
</div>
