<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="icon" href="/web/dashboard/images/codeigniter.png" type="image/x-icon" />
    <link rel="shortcut icon" href="/web/dashboard/images/codeigniter.png" type="image/x-icon" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php if(isset($data['title'])) echo $data['title']; else echo 'Админ. панель'?></title>

    <!-- Bootstrap -->
    <link href="/web/dashboard/css/bootstrap.css" rel="stylesheet">
    <link href="/web/dashboard/css/font-awesome.css" rel="stylesheet">
    <script src="/web/dashboard/js/jquery-1.11.1.js"></script>
    <link href="/web/dashboard/css/jquery.datetimepicker.css" rel="stylesheet">
    <style>
        .nav > li {
            width: 100%;
        }
<?php
/*
        .nav > li a[href="/web/dashboard/index.php/adminka/page/<?php echo $this->uri->segment(3);?>"]{
            background: #fff;
        }
        <? if($this->uri->segment(2)=='media'):?>
        .nav > li a[href="/web/dashboard/index.php/adminka/media"]{
            background: #fff;
        }
        <? endif;?>
*/ ?>
    </style>
    <script src="/web/dashboard/download/ckeditor/ckeditor.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="/web/dashboard/js/html5shiv.min.js"></script>
    <script src="/web/dashboard/js/respond.min.js"></script>
    <![endif]-->
</head>
<body style="background: #222;">



<nav class="navbar navbar-inverse" role="navigation" style="text-align: right; height: 10px; padding-bottom: 0px; margin-bottom: 0px; padding-top: 7px;">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <!--<div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Навигация</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <!--  <a class="navbar-brand my-brand" href="/"><img src="/web/dashboard/images/logo.jpg" width="60" /></a> -->
        <!--</div>-->
        <a href="/logout" class="btn btn-danger">Выход</a>
        <!-- Collect the nav links, forms, and other content for toggling
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
		<?php echo $data['adminMenu']; ?>
	  </ul>
   </div> /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-2" id="my-wrap">

            <ul class="nav navbar-nav">
                <?php echo $data['adminMenu']; ?>
            </ul>

        </div>