<div class="col-md-8" id="my-wrap" style="background: #fff;">
    <form role="form" method="post" action="/dashboard">
        <div class="form-group">
            <label for="login">Login</label>
            <input type="text" class="form-control" id="login" name="login" placeholder="Enter login">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
        </div>
        <button type="submit" class="btn btn-default">Войти</button>
    </form>
</div>