<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% if title != false %}{{ title }}{% else %}Basic title{% endif %}</title>
    {% block stylesheets %}
    <link rel="stylesheet" href="/web/bootstrap/css/bootstrap.min.css" />
    {% endblock %}
    {% block scripts %}
    <script type="text/javascript" src="/vendor/bower-asset/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/vendor/bower-asset/bootstrap/dist/js/bootstrap.min.js"></script>
    <!--<script type="text/javascript" src="/vendor/bower-asset/bootstrap/dist/js/npm.js"></script>-->
    <script type="text/javascript" src="/vendor/bower-asset/react/react.min.js"></script>
    <script type="text/javascript" src="/vendor/bower-asset/react/react-dom.min.js"></script>
    <script type="text/javascript" src="/vendor/bower-asset/react/react-dom-server.min.js"></script>
    {% endblock %}
</head>
<body>
<div class="container">
    <div class="row">
        {% if app.session.isAdmin != false %}
            <a href="/comment/logout">Выйти</a>
        {% else %}
            <a href="/comment/login">Войти в админку</a>
        {% endif %}